image: node:lts

pages:
    stage: deploy
    script:
        - npm install
        - npm run build
        - rm -r public/
        - mv dist/ public/
    artifacts:
        paths:
            - public
